
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqnpyzjetasvztootdad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbnB5empldGFzdnp0b290ZGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzM0MjgsImV4cCI6MjA1OTYwOTQyOH0.KBg92fhkTw_VHf6yCavpunBQwcGyM-SbEa1qx4fTwB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define types for MoodEntry until we can update the generated types
export type MoodEntry = {
  id: string;
  user_id: string;
  mood: number;
  energy: number;
  sleep: number;
  date: string;
  notes?: string;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Use direct table access
export const moodEntriesTable = () => {
  return supabase.from('mood_entries');
};
